network:
  version: 2
  renderer: networkd
  ethernets:
% for eth in set(vlan['interface'] for vlan in vlans):
    ${eth}:
      accept-ra: no
% endfor
  vlans:
% for vlan in vlans:
  % if vlan['vlan_id']:
    ${vlan['interface']}.${vlan['vlan_id']}:
      accept-ra: no
      id: ${vlan['vlan_id']}
      link: ${vlan['interface']}
  % endif
% endfor
  bridges:
    ${bridge_name}:  
      interfaces:
% for vlan in vlans:
  % if vlan['vlan_id']:
        - ${vlan['interface']}.${vlan['vlan_id']}
  % else:
        - ${vlan['interface']}
  % endif
% endfor

