description "IDS logger to Central Manager"

start on filesystem or runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5

env PYTHONPATH=/opt/origin/lib/python

exec /opt/origin/sbin/connection-trackerd

pre-start script
	# eth0 is wan interface
	# eth1 is lan interface
	if ! iptables-save | grep -q 'FORWARD *-m *physdev *--physdev-in *eth. *-j *NFLOG *--nflog-prefix *IN'
	then
		iptables  -I FORWARD -m physdev --physdev-in  eth0 -j NFLOG --nflog-prefix IN
		iptables  -I FORWARD -m physdev --physdev-out eth0 -j NFLOG --nflog-prefix OUT
		ip6tables -I FORWARD -m physdev --physdev-in  eth0 -j NFLOG --nflog-prefix IN
		ip6tables -I FORWARD -m physdev --physdev-out eth0 -j NFLOG --nflog-prefix OUT
	fi
end script
