#!/usr/bin/env python3

from origin.captive_portal import GuestAccessManager
from origin.neuron import Dendrite

if __name__ == "__main__":
    dendrite = Dendrite()
    manager = GuestAccessManager(dendrite)
    dendrite(manager.new_authorizations)

    
    manager.start()