#!/usr/bin/env python3

from origin.captive_portal import GuestAccessManager
from origin.neuron import Dendrite

if __name__ == "__main__":
    dendrite = Dendrite()
    manager = GuestAccessManager(dendrite)
    dendrite.subscribe_conf('guest-access/active-authorizations', manager.new_authorizations)

    
    dendrite.wait_complete()
