#!/usr/bin/env python3

import time
from origin.nac.manager import MacAuthorizationManager

if __name__ == "__main__":
    conf = MacAuthorizationManager()
    count = 1
    while count < 100:
        conf.run_for_ever()
        time.sleep(5)
        count = count + 1
