#!/usr/bin/env python3

from origin.nac.manager import MacAuthorizationManager, AUTHORIZATION_CHANGE_TOPIC, DISCONNECT_NOTIFICATION_TOPIC
from origin.neuron import AsyncDendrite

if __name__ == "__main__":
    dendrite = AsyncDendrite()
    manager = MacAuthorizationManager(dendrite=dendrite)
    
    dendrite.subscribe(AUTHORIZATION_CHANGE_TOPIC, manager.handle_authz_changed)
    dendrite.subscribe(DISCONNECT_NOTIFICATION_TOPIC, manager.handle_disconnection)
   # TODO ? provide(CHECK_AUTHZ_PATH, call_cb) ?

    dendrite.run()
