'''This file is automatically generated by autoconf's configure'''

__package_name__ = 'wirepy'
__version__ = '0.1'

CFLAGS = '-I/usr/include/wireshark -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  '
LIBS = '-lwireshark -lglib-2.0  '

# basic type to expect for gint64
GINT64TYPE = 'long'

# TODO: This is not portable at all...
CFLAGS = list(filter(None, map(str.strip, CFLAGS.split(' '))))
LIBS = list(filter(None, map(str.strip, LIBS.split(' '))))
